; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "selaras-scanner-setup"
#define MyAppVersion "1.0.1"
#define MyAppPublisher "Selaras"
#define MyAppExeName "SelarasScanner.exe"
#define MyAppAssocName MyAppName + ""
#define MyAppAssocExt ".exe"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{97650377-A6CA-41DC-B557-212828DC8BAC}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\syahroni\Desktop
OutputBaseFilename=selaras-scanner-setup
SetupIconFile=D:\kerja\selaras_frontend\public\favicon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\kerja\selaras_frontend\scanner-service\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\kerja\selaras_frontend\scanner-service\dist\run.vbs"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

; [Run]
; Membersihkan task lama (jika ada) secara diam-diam
; Filename: "schtasks"; Parameters: "/delete /tn ""SelarasScanner"" /f"; Flags: runhidden; StatusMsg: "Menyiapkan sistem..."

; Membuat task scheduler untuk memanggil VBS agar aplikasi berjalan tanpa jendela CMD
; Filename: "schtasks"; Parameters: "/create /tn ""SelarasScanner"" /tr ""wscript.exe \""{app}\run.vbs\"""" /sc onlogon /rl highest /delay 0000:05 /f"; Flags: runhidden; StatusMsg: "Mendaftarkan background service..."

; Langsung menyalakan aplikasi setelah proses instalasi selesai
; Filename: "schtasks"; Parameters: "/run /tn ""SelarasScanner"""; Flags: runhidden; StatusMsg: "Menjalankan Selaras Scanner..."

[Run]
    ; Membersihkan task lama (jika ada) secara diam-diam
    Filename: "schtasks"; Parameters: "/delete /tn ""SelarasScanner"" /f"; Flags: runhidden; StatusMsg: "Menyiapkan sistem..."

    ; Membuat task scheduler untuk memanggil VBS agar aplikasi berjalan otomatis saat Windows Startup
    Filename: "schtasks"; Parameters: "/create /tn ""SelarasScanner"" /tr ""wscript.exe """"{app}\run.vbs"""""" /sc onlogon /rl highest /f"; Flags: runhidden;StatusMsg: "Mendaftarkan background service..."

    ; Langsung menyalakan aplikasi VBS secara langsung saat installer selesai
    Filename: "wscript.exe"; Parameters: """{app}\run.vbs"""; Flags: runhidden;StatusMsg: "Menjalankan Selaras Scanner..."

[UninstallRun]
; Mematikan aplikasi dan menghapus task scheduler saat pengguna melakukan Uninstall
Filename: "taskkill"; Parameters: "/F /IM SelarasScanner.exe"; Flags: runhidden; RunOnceId: "StopSelarasScanner"
Filename: "schtasks"; Parameters: "/delete /tn ""SelarasScanner"" /f"; Flags: runhidden; RunOnceId: "DeleteSelarasScannerTask"
