import crypto from "crypto";
import { ScannerApplication, ScannerConfiguration } from "./types";

// function untuk generate identifier GUID unik untuk installer Inno Setup
export function generateGuid(): string {
  return crypto.randomUUID().toUpperCase();
}

// function untuk menghitung nilai hash SHA-256 untuk verifikasi integritas file
export function generateSha256(content: string): string {
  return crypto.createHash("sha256").update(content).digest("hex");
}

// function untuk generate script VBScript agar scanner agent berjalan di background tanpa jendela CMD
export function generateVbsScript(app: ScannerApplication, config: ScannerConfiguration): string {
  const exeName = config.executableName || `${app.name.replace(/[^a-zA-Z0-9]/g, "")}.exe`;
  return `' ==============================================================================
' Runner VBScript for ${app.name} (${app.id})
' Auto-generated by Scanner Platform
' ==============================================================================
Set WshShell = CreateObject("WScript.Shell")
Set objFSO = CreateObject("Scripting.FileSystemObject")

strFolder = objFSO.GetParentFolderName(WScript.ScriptFullName)
WshShell.CurrentDirectory = strFolder

' Execute background scanner agent without showing CMD window
WshShell.Run chr(34) & strFolder & "\\${exeName}" & Chr(34), 0, False

Set WshShell = Nothing
Set objFSO = Nothing
`;
}

// function untuk generate script Inno Setup (.iss) untuk kompilasi installer Windows resmi
export function generateInnoSetupScript(app: ScannerApplication, config: ScannerConfiguration, guid?: string): string {
  const cleanGuid = guid || generateGuid();
  const slug = app.name.toLowerCase().replace(/[^a-z0-9]/g, "-");
  const exeName = config.executableName || `${app.name.replace(/[^a-zA-Z0-9]/g, "")}.exe`;
  const installerBase = config.installerName ? config.installerName.replace(/\.exe$/i, "") : `${slug}-setup`;
  const taskName = app.name.replace(/[^a-zA-Z0-9]/g, "");

  return `; ==============================================================================
; Inno Setup Script for ${app.name}
; Application ID: ${app.id}
; Version: ${config.agentVersion || "2.1.0"}
; Generated by Scanner Platform
; ==============================================================================

#define MyAppName "${slug}-setup"
#define MyAppVersion "${config.agentVersion || "2.1.0"}"
#define MyAppPublisher "${app.companyName || "Scanner Service"}"
#define MyAppExeName "${exeName}"
#define MyAppAssocName MyAppName + ""
#define MyAppAssocExt ".exe"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
AppId={{${cleanGuid}}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\\{#MyAppName}
UninstallDisplayIcon={app}\\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
OutputBaseFilename=${installerBase}
OutputDir=.
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "dist\\run.vbs"; DestDir: "{app}"; Flags: ignoreversion
Source: "config.json"; DestDir: "{app}"; Flags: ignoreversion

[Registry]
Root: HKA; Subkey: "Software\\Classes\\{#MyAppAssocExt}\\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\\Classes\\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\\Classes\\{#MyAppAssocKey}\\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\\Classes\\{#MyAppAssocKey}\\shell\\open\\command"; ValueType: string; ValueName: ""; ValueData: """{app}\\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\\{#MyAppName}"; Filename: "{app}\\{#MyAppExeName}"
Name: "{autodesktop}\\{#MyAppName}"; Filename: "{app}\\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; Bersihkan task lama (jika ada) secara diam-diam
Filename: "schtasks"; Parameters: "/delete /tn ""${taskName}"" /f"; Flags: runhidden; StatusMsg: "Menyiapkan sistem..."

; Membuat task scheduler untuk memanggil VBS agar aplikasi berjalan otomatis saat Windows Startup
Filename: "schtasks"; Parameters: "/create /tn ""${taskName}"" /tr ""wscript.exe """"{app}\\run.vbs"""""" /sc onlogon /rl highest /f"; Flags: runhidden; StatusMsg: "Mendaftarkan background service..."

; Langsung menyalakan aplikasi VBS secara langsung saat installer selesai
Filename: "wscript.exe"; Parameters: """{app}\\run.vbs"""; Flags: runhidden; StatusMsg: "Menjalankan ${app.name}..."

[UninstallRun]
; Mematikan aplikasi dan menghapus task scheduler saat uninstall
Filename: "taskkill"; Parameters: "/F /IM ${exeName}"; Flags: runhidden; RunOnceId: "Stop${taskName}"
Filename: "schtasks"; Parameters: "/delete /tn ""${taskName}"" /f"; Flags: runhidden; RunOnceId: "Delete${taskName}Task"
`;
}

// function untuk generate script batch setup Windows (.bat) yang mendaftarkan task scheduler
export function generateBatchInstaller(app: ScannerApplication, config: ScannerConfiguration): string {
  const exeName = config.executableName || `${app.name.replace(/[^a-zA-Z0-9]/g, "")}.exe`;
  const taskName = app.name.replace(/[^a-zA-Z0-9]/g, "");
  const targetDir = `C:\\${taskName}\\scanner`;
  const defaultPort = config.defaultPort || 2019;

  return `@echo off
setlocal enabledelayedexpansion
title ${app.name} - Installer

:: --- Cek hak akses Administrator ---
net session >nul 2>&1
if %errorLevel% neq 0 (
    echo.
    echo  [!] Installer ini membutuhkan hak akses Administrator.
    echo      Klik kanan file ini lalu pilih "Run as administrator"
    echo.
    pause
    exit /b 1
)

echo.
echo  =====================================================
echo    ${app.name} - Installer v${config.agentVersion || "2.1.0"}
echo    Application ID: ${app.id}
echo  =====================================================
echo.
echo  Menginstall scanner service...
echo.

:: --- Variabel ---
set INSTALL_DIR=${targetDir}
set TASK_NAME=${taskName}
set EXE_NAME=${exeName}
set SCRIPT_DIR=%~dp0

:: --- [1/4] Buat folder instalasi ---
echo  [1/4] Menyiapkan folder instalasi...
if not exist "%INSTALL_DIR%" mkdir "%INSTALL_DIR%"

:: Copy Executable & Config
if exist "%SCRIPT_DIR%%EXE_NAME%" (
    copy /Y "%SCRIPT_DIR%%EXE_NAME%" "%INSTALL_DIR%\\%EXE_NAME%" >nul
    echo      OK: %EXE_NAME% disalin ke %INSTALL_DIR%
) else (
    echo  [!] ERROR: File %EXE_NAME% tidak ditemukan.
    pause
    exit /b 1
)

if exist "%SCRIPT_DIR%config.json" (
    copy /Y "%SCRIPT_DIR%config.json" "%INSTALL_DIR%\\config.json" >nul
)

:: --- [2/4] Bersihkan instalasi lama ---
echo.
echo  [2/4] Membersihkan instalasi lama...
sc stop %TASK_NAME% >nul 2>&1
sc delete %TASK_NAME% >nul 2>&1
schtasks /delete /tn "%TASK_NAME%" /f >nul 2>&1
echo      OK: Instalasi lama dibersihkan.

:: --- [3/4] Daftarkan via Task Scheduler ---
echo.
echo  [3/4] Mendaftarkan Task Scheduler...
for /f "tokens=1" %%u in ('whoami') do set CURRENT_USER=%%u

schtasks /create /tn "%TASK_NAME%" ^
    /tr "\\"^%INSTALL_DIR^%\\^%EXE_NAME^%\\"" ^
    /sc onlogon ^
    /rl highest ^
    /delay 0000:10 ^
    /f >nul 2>&1

if %errorLevel% neq 0 (
    echo  [!] ERROR: Gagal mendaftarkan Task Scheduler.
    pause
    exit /b 1
)
echo      OK: Task terdaftar - otomatis start saat login.

:: --- [4/4] Jalankan sekarang ---
echo.
echo  [4/4] Menjalankan service...
schtasks /run /tn "%TASK_NAME%" >nul 2>&1
timeout /t 3 /nobreak >nul

:: --- Verifikasi ---
powershell -NoProfile -Command ^
    "try { $r = Invoke-WebRequest -Uri 'http://127.0.0.1:${defaultPort}/health' -UseBasicParsing -TimeoutSec 5; if ($r.StatusCode -eq 200) { exit 0 } else { exit 1 } } catch { exit 1 }" >nul 2>&1

if %errorLevel% equ 0 (
    echo.
    echo  =====================================================
    echo   [OK] Instalasi ${app.name} berhasil!
    echo  =====================================================
    echo.
    echo   Scanner service berjalan di background.
    echo   Otomatis start setiap kali Windows login.
    echo   Cek status: http://127.0.0.1:${defaultPort}/health
    echo.
) else (
    echo.
    echo  =====================================================
    echo   [!] Service terinstall tapi belum merespons di port ${defaultPort}.
    echo  =====================================================
    echo   Jika port lain digunakan karena port hunting, cek http://127.0.0.1/
    echo.
)

pause
exit /b 0
`;
}

// function untuk generate file konfigurasi json runtime (config.json) untuk desktop agent
export function generateAgentConfigFile(app: ScannerApplication, config: ScannerConfiguration): string {
  return JSON.stringify(
    {
      applicationId: app.id,
      applicationName: app.name,
      version: config.agentVersion || "2.1.0",
      executableName: config.executableName || `${app.name.replace(/[^a-zA-Z0-9]/g, "")}.exe`,
      installerName: config.installerName || `${app.name.replace(/[^a-zA-Z0-9]/g, "")}-Setup.exe`,
      defaultPort: config.defaultPort || 2019,
      portRange: [config.portRangeStart || 2019, config.portRangeEnd || 2030],
      host: config.host || "127.0.0.1",
      allowedOrigins: config.allowedOrigins && config.allowedOrigins.length > 0 ? config.allowedOrigins : ["*"],
      logLevel: config.logLevel || "INFO",
      logToFile: config.logToFile !== false,
      enableMockDev: Boolean(config.enableMockDev),
    },
    null,
    2
  );
}
